const NORMAL_TEXT_FILL = '#666';
const NORMAL_TEXT_STROKE = '#999';
const NORMAL_TEXT_STROKE_THICKNESS = 4;
const NORMAL_TEXT_FONT = 'origicide';
const NORMAL_TEXT_FONT_SIZE = 32;
const TEXT_STYLE = {
  font: NORMAL_TEXT_FONT,
  fill: NORMAL_TEXT_FILL,
  stroke: NORMAL_TEXT_STROKE,
  strokeThickness: NORMAL_TEXT_STROKE_THICKNESS,
  fontSize: NORMAL_TEXT_FONT_SIZE
};

module.exports = {
  DEFAULT_TEXT_STYLE: TEXT_STYLE,
  NORMAL_TEXT_FILL: NORMAL_TEXT_FILL,
  NORMAL_TEXT_STROKE: NORMAL_TEXT_STROKE,
  NORMAL_TEXT_STROKE_THICKNESS: NORMAL_TEXT_STROKE_THICKNESS,
  NORMAL_TEXT_FONT: NORMAL_TEXT_FONT,
  NORMAL_TEXT_FINT_SIZE: NORMAL_TEXT_FONT_SIZE
};
